$(document).ready(function(){
  $("p").hide();
  $("#btn").click(function(){
      if ($("p").is(":hidden")==true){
          $("p").show();
          $("#btn").val('submitt');
      }
      else{
        $("p").hide();
        $("#btn").val('show');
      }
  });
  $("#img").hide();
  $("#btn2").click(function(){
    if($("#img").is(":hidden")==true){
       $("#img").show();
       $("#btn2").val('submitt');
    }
    else{
      $("#img").hide();
      $("btn2").val('show');
    }
  });
  $("#img1").hide();
  $("#btn3").click(function(){
    if($("#img1").is(":hidden")==true){
      $("#img1").show();
      $("#btn3").val('submitt');
    }
    else{
      $("#img1").hide();
      $("btn3").val('show');
    }
  });
  $("#img2").hide();
  $("#btn4").click(function(){
    if($("#img2").is(":hidden")==true){
      $("#img2").show();
      $("#btn4").val('submitt');
    }
    else{
      $("#img2").hide();
      $("btn4").val('show');
    }
  });
  $("#img3").hide();
  $("#btn5").click(function(){
    if($("#img3").is(":hidden")==true){
      $("#img3").show();
      $("#btn5").val('submitt');
    }
    else{
      $("#img3").hide();
      $("btn5").val('show');
    }
  });
  $("#img4").hide();
  $("#btn6").click(function(){
    if($("#img4").is(":hidden")==true){
      $("#img4").show();
      $("#btn6").val('submitt');
    }
    else{
      $("#img4").hide();
      $("btn6").val('show');
    }
  });
  $("#img5").hide();
  $("#btn7").click(function(){
    if($("#img5").is(":hidden")==true){
      $("#img5").show();
      $("#btn7").val('submitt');
    }
    else{
      $("#img5").hide();
      $("btn7").val('show');
    }
  });
});
